### ISSUE TITLE
When click ‘’Train and Visualize‘’button，nothing happens.

### ISSUE THREAD

**Issue by lcgsglance** [fredhohman/shapeshop#8]
There is nothing to show that the program is working .Does it take a long time to calculate?

**Comment by fredhohman** [comment]
Hi @zionzheng,

It should not take a long time to compute.
Make sure you carefully read the installation guidelines, as this project is using older versions of Keras and TensorFlow.

See here: https://github.com/fredhohman/shapeshop#requirements-python-35

If you still can't get it to work, from the terminal you should see output from the python backend that may throw some errors—that could be telling of what isn't working. Post those here if that's the case.

**Comment by lcgsglance** [comment]
Your suggestion is very useful.I used a much newer version of numpy.Thanks for helping me to open this'blackbox‘：)

**Comment by fredhohman** [comment]
Wonderful!
